all: thread1 thread3 thread4 thread7 thread8

thread1: thread1.c
	gcc -pthread -o thread1 thread1.c

thread3: thread3.c
	gcc -pthread -o thread3 thread3.c
	
thread4: thread4.c
	gcc -pthread -o thread4 thread4.c

thread7: thread7.c
	gcc -pthread -o thread7 thread7.c

thread8: thread8.c
	gcc -pthread -o thread8 thread8.c
